//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.10

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "users")]
pub struct Model {
    pub created_at: String,
    pub updated_at: String,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub pid: String,
    pub email: String,
    pub password: String,
    pub api_key: String,
    pub name: String,
    pub reset_token: Option<String>,
    pub reset_sent_at: Option<String>,
    pub email_verification_token: Option<String>,
    pub email_verification_sent_at: Option<String>,
    pub email_verified_at: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}
