[package]
name = "test01"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.20"
reqwest = { version = "0.11.23", features = ["blocking", "json"] }
zabbix-api = "0.1.0"

